export default {
  "login": "simonw",
  "id": 9599,
  "node_id": "MDQ6VXNlcjk1OTk=",
  "avatar_url": "https://avatars.githubusercontent.com/u/9599?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/simonw",
  "html_url": "https://github.com/simonw",
  "followers_url": "https://api.github.com/users/simonw/followers",
  "following_url": "https://api.github.com/users/simonw/following{/other_user}",
  "gists_url": "https://api.github.com/users/simonw/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/simonw/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/simonw/subscriptions",
  "organizations_url": "https://api.github.com/users/simonw/orgs",
  "repos_url": "https://api.github.com/users/simonw/repos",
  "events_url": "https://api.github.com/users/simonw/events{/privacy}",
  "received_events_url": "https://api.github.com/users/simonw/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Simon Willison",
  "company": "Datasette",
  "blog": "https://simonwillison.net/",
  "location": "Half Moon Bay, CA",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": "simonw",
  "public_repos": 702,
  "public_gists": 281,
  "followers": 5054,
  "following": 136,
  "created_at": "2008-05-07T17:22:14Z",
  "updated_at": "2023-09-02T14:34:32Z",
};
